\clearpage

# Abstract {-}

**Title:** `r rmarkdown::metadata$title`:  `r rmarkdown::metadata$subtitle`   
**Author:** `r rmarkdown::metadata$author`    
**Keywords:** Incubators; Accelerators; Startups; Entrepreneurship; Innovation.

&nbsp;

The European startup and investment scene is quickly expanding: record levels of growth were identified in 2021, revealing this region lacks only in maturity of the ecosystem. Startup accelerators - the new generation of incubators - have picked up on this expansion and turned acceleration into a successful venture. As researchers continue to disagree on the conceptual and typological definitions of startup accelerators, their impact and ideal structure remain unclear. This dissertation aims to transpose a study conducted in the USA startup ecosystem to the European reality through intensive use of data and statistics. It looks into the relationships between the design variables of acceleration programs and the success - or lack thereof - of their graduated startups. Data was collected through a range of aggregators, news articles and websites and put through linear regression models in order to test the hypothesis that an accelerator's structure impacts its startup's chances of success. Our results reflect the positive effects of a large and diversified network of partners, sponsors, founders, and companies but struggled to explain the mechanisms behind startup success in full. Our data allowed us to distinguish between ill- and well-designed accelerators, establishing that the impact of the latter is stronger in both the short- and long-term, ultimately proposing the structure for an accelerator that maximises a startup's chances of success.
