\clearpage

# Conclusion and Implications

## Theoretical Implications

The outcome of our analysis is exciting and only more thrilling after a lengthy data collection process. To be met with statistical significance, one may be led to believe they have struck gold and put forward a misleading message. Three out of the four implemented regressions in Section \@ref(hypothesis1) were shown to be statistically significant, therefore revealing the answer to the RQ1 “Do accelerator program design variables affect a graduated startup's chance of success?”: there is a significant correlation between the design elements of startup accelerators on their cohort of accelerated firms in the European context.

Nonetheless, other factors should be taken into account and other statistics should be considered, namely the R-squared (R^2^), used to determine the explanatory power of the model under analysis. Regression (1) in Table \@ref(tab:acccompanyperformanceaccdesign) explains `r round(summary(acc_company_performance_acc_design_m1)$r.squared * 100, 1)`% of the performance outcome, regression (2) `r round(summary(acc_company_performance_acc_design_m2)$r.squared * 100, 1)`%, regression (3) `r round(summary(acc_company_performance_acc_design_m3)$r.squared * 100, 1)`%, and regression (4), the one missing statistical significance, `r round(summary(acc_company_performance_acc_design_m4)$r.squared * 100, 1)`%. Although this measure does not indicate in full to what extent the data and models should be trusted, it indicates the influence and importance of other factors in understanding the mechanisms behind the startup and, consequently, accelerator success. These will be human, psychological, historical, social, economic, and other anthropological characteristics of host countries and cities, managers and founders, and even entrepreneurs. Negative coefficients and thus negative impact of certain design variables may hold true to @yu_accelerators_2020's hypothesis that states an accelerator's main impact is in lowering unpredictability for startups that end their activity earlier after realizing their product or service is not fit for further development or investment. Nevertheless, the tests uncovered other, more positive trends such as the impact of the background of sponsors, managers and founders of accelerators and other structural elements of their programs.

We were also able to confirm certain trends disclosed by @cohen_accelerating_2014: firstly, data is hard to find and often only available behind pay-walls and time-consuming interview and research processes. Secondly, the impact of accelerators on their cohort of startups is often unclear and sometimes negative. Interactions with external stakeholders such as companies, investors, government organizations, and academic institutions are typically statistically significant, displaying a positive relationship with success metrics. The third-generation incubation model by @bruneel_evolution_2012 that theorizes a value proposition deriving from networking is seen reflected in these results, pushing the idea that research is moving in the right direction. Accelerator founders and managing directors did not describe such strong connections to successful startups, seeing mixed results both in terms of statistical significance and coefficients. Their role in establishing entry criteria and program curriculum is still apparent and in accordance with @tripathi_insights_2019, but there are other factors at play, out of an accelerator's control. Funding made available to startups for participating in acceleration programs had no impact on their performance both long- and short-term, placing an even larger emphasis on the effects of mentoring and networking. 

An interesting characteristic of the chosen startup performance indicators is their intrinsic connection to a startup's lifespan. “Received > \$500K within 1 year” can be linked to their earliest stages whereas “Total Raised”, “Max Valuation”, and “Exit of \$1M or More” are tied to long-term goals of companies who have grown to be scale-ups. Only well-designed accelerators can get their cohort of startups to achieve good results in the short-term: the probability of startups raising at least $500K in the year following their graduation is higher for those coming from these programs. In answering RQ2 “Are there performance differences between startups who graduated from ill- and well-designed accelerator programs?”, in the long term, only those startups who have had the support of a great accelerator (a well-designed accelerator) were shown to bring about more raised capital, reflecting the lifelong impact an accelerator can have in the company.

## Managerial Implications: How to Design an Accelerator Program to Maximize Its Cohort's Chances of Success

One of the main objectives of this dissertation is to address how managers and founders of startup accelerators can increase their chances of success: the better the outcome for startups, the more likely the benefits for the accelerator. For many programs, the reward comes once their investments have a successful exit. Ideally, we would look to the fourth column in Table \@ref(tab:acccompanyperformanceaccdesign) which depicts the relationship between accelerator design elements and the startup outcome metric “Exit of \$1M or More”. Unfortunately, as previously addressed, no statistical significance was found for this model. Instead, we can look to “Total Raised” as the second-best measure for accelerator impact as this metric has been shown to be strongly related to the analyzed design variables. We can also address the results of the comparison between ill- and well-designed accelerators that demonstrates the impact a first-class acceleration program can have on the long-term success of startups. 

In order to build a successful accelerator, managers and founders must craft close connections with partners from governmental institutions and the investment industry in order to convey their knowledge of business, experience, and expertise to the startups they are investing in, focusing on mentorship of what they know about working as a company and on how to attract investors and make the best use of raised capital. Accelerators need to build a great internal team, capable of providing a structured program with workshops, talks, and mentorship sessions. Great acceleration programs should run for close to a year to give startups enough time to take in all provided information and to share their learnings and experiences with the cohort with which they share a workspace. In the end, small amounts of funding in exchange for around 2% of equity and a team that is committed to the success of their startups will make a difference. On the whole, acceleration is about speeding up the process of building a startup that can sustain its growth. A large and wide network is a great first step in that direction and accelerators should make that their goal.

In the future, more and more acceleration-type programs will come to be like the current growth in numbers suggests. Innovation will keep leading the money and computers will be given the task of finding trends for markets, industries, and technologies. Just as we have seen the first-generation incubator develop around shared office space, the second-generation incubator thrive on shared services, and the third-generation incubator rest on a shared network of people and organisations, perhaps the fourth-generation incubator is nearing, with its data-driven methodologies and insights that add value to the startups and companies that go through their programs.
