\clearpage

# Limitations and Future Research

Researchers remain puzzled by the definition of incubators, accelerators, and similar programs. Although the typology classification system proposed in Section \@ref(typologyclassification) is a good fit for all accelerators examined in this study, it places programs inside a box that is either too large or provides too narrow of a definition which comes short of what these accelerators require. Borderless research - one fitting for all early-stage, pre-seed, and seed programs from all regions - is imperative. 

Even though our study confirms certain theories regarding the impact of sponsors and networks on startups, other analysed variables showed diverging results, many of them portraying negative relationships. This begs the question: what other mechanisms are at play? Is there a better way to measure startup and accelerator success? Furthermore, it is important to underline the reduced explanatory power of the variables this study has used to predict startup success after acceleration. Understanding which elements of the programs are defining for the structure of an accelerator will make this statistical approach more informative.

Initially, 886 accelerators were identified but only `r round(nrow(acc_design_choices)/886 * 100, 0)`% of these programs are accounted for in the final dataset. Even though no discriminatory policies were applied when conducting this research, accelerators that are currently in business and those that adopt a digital strategy for communication are more likely to be part of this list. A more comprehensive investigation encompassing a study group that truthfully and completely reflects the real population and usage of better, more fitting statistical methods could provide more significant results. Moreover, while the data sources used in this research are validated, this method is not a match for nor does it substitute interviewing the managers and founders of programs as was done in the paper used as reference by @cohen_design_2019. Understanding the differences between American and European accelerators and comparing the current state of incubation in both regions could provide researchers with an outlook of the future for the latter, given that Europe is just now reaching the maturity levels of the USA in terms of startup and venture development [@european_tech_2021]. It would also be interesting to understand the impact that the current pandemic scenario and implicit shift to remote working has had in accelerators and in the way they interact with startups, mentors, and sponsors.

All things considered, we identify the need for further research in all three verticals put forward by @hausberg_business_2020: typology, process, and performance of accelerators. The latter, impact and performance, due to its potential meaning for managers, entrepreneurs and investors, could be seen as the most relevant. Through extended research, interviews, and data collection over better statistical approaches, this academic effort may allow managers to make better decisions on how to structure an acceleration program and enhance the chances of success for incubated startups. The foundations have been laid for a study on the impact of accelerators in the European region, translated from the USA ecosystem. In an ever-so-competitive landscape, the writer of this dissertation is enthusiastic about this field of research and its implications and intends to proceed to a doctoral program with the learnings resulting from this dissertation. They have begun the process of interviewing accelerator program managers with the purpose of data and trend confirmation, a lengthy process that should be pursued in due time. We firmly believe analytical methodologies will give accelerators the edge they need to win the startup game.